"use client";

// import type { Metadata } from "next";
import { ThemeProvider } from "../components/theme-provider";
import { Geist, Azeret_Mono as Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "../components/navbar";
import { useScroll, motion, useTransform } from "framer-motion";
import type React from "react"; // Added import for React

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { scrollY } = useScroll();
  const navbarY = useTransform(scrollY, [0, 100], [-100, 0]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <motion.div
            style={{
              position: "fixed",
              top: 0,
              left: 0,
              right: 0,
              y: navbarY,
              zIndex: 1000,
            }}
          >
            <Navbar />
          </motion.div>
          <main className="">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
